name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Determine tag
      run: echo "TAG_NAME=$(date +%s)" >> $TAG_NAME
    
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/doomflute:$TAG_NAME
      

    - name: Push to dockerhub
      run: docker push ${{secrets.DOCKER_USER}}/doomflute:$TAG_NAME
